name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main 

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install and Fix Dependencies
        run: |
          # 1. 强制安装正常版本的 ajv 及其缺失模块
          npm install ajv ajv-keywords --save-dev
          # 2. 忽略冲突安装其他依赖
          npm install --legacy-peer-deps

      - name: Build
        run: |
          # 忽略警告直接打包
          export CI=false
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
