name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main 

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install and Build
        run: |
          # 所有安装指令都必须加上强行忽略冲突的后缀
          npm install --legacy-peer-deps
          npm install ajv ajv-keywords --legacy-peer-deps
          
          # 忽略警告直接打包
          export CI=false
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
